title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"
repo: ucsb-cs156-f24/team02-f24-12
owner: ucsb-cs156-f24
repo_name: team02-f24-12
pull_requests: [{"author":{"id":"U_kgDOB8qFRw","is_bot":false,"login":"Abby-Fan04","name":""},"headRefName":"abby-team03","number":135,"title":"Abby team03 testsss","url":"https://github.com/ucsb-cs156-f24/team02-f24-12/pull/135"},{"author":{"id":"MDQ6VXNlcjMwNjMzMDE5","is_bot":false,"login":"mayarosenbaum","name":""},"headRefName":"maya-helpRequestForms","number":131,"title":"mr - added help request table and tests, pages and tests","url":"https://github.com/ucsb-cs156-f24/team02-f24-12/pull/131"}]
